"""esquema inicial

El esquema tal como estaba en producción al adoptar Alembic (octubre 2026),
ajustado a mano para que coincida con la base real: ON DELETE CASCADE en las
FK, TEXT/NUMERIC donde la base los tiene, índices con sus nombres reales.

- Base de producción (ya tenía todo esto, creado por create_all + SQL a mano):
  NO se corre; se marca con `alembic stamp 0001`.
- Base nueva y vacía: `alembic upgrade head` la crea desde cero.

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 10:46:14.916336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_amenities_id'), 'amenities', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('owner_phone', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('owner_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('season_start', sa.Integer(), nullable=True),
    sa.Column('season_end', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('public_transport', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_spots_category_id'), 'spots', ['category_id'], unique=False)
    op.create_index(op.f('ix_spots_created_at'), 'spots', ['created_at'], unique=False)
    op.create_index(op.f('ix_spots_department'), 'spots', ['department'], unique=False)
    op.create_index(op.f('ix_spots_id'), 'spots', ['id'], unique=False)
    op.create_index(op.f('ix_spots_is_approved'), 'spots', ['is_approved'], unique=False)
    op.create_index(op.f('ix_spots_owner_deleted_at'), 'spots', ['owner_deleted_at'], unique=False)
    op.create_index(op.f('ix_spots_owner_email'), 'spots', ['owner_email'], unique=False)
    op.create_table('camping_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_table('climbingsectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('max_altitude', sa.Integer(), nullable=True),
    sa.Column('restrictions', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climbingsectors_id'), 'climbingsectors', ['id'], unique=False)
    op.create_index(op.f('ix_climbingsectors_spot_id'), 'climbingsectors', ['spot_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiences_category_id', 'experiences', ['category_id'], unique=False)
    op.create_index('idx_experiences_spot_id', 'experiences', ['spot_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_id', name='uq_user_spot')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('glamping_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_type', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=True),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glamping_details_spot_id'), 'glamping_details', ['spot_id'], unique=False)
    op.create_table('kayak_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('water_type', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('kayak_type', sa.String(), nullable=True),
    sa.Column('rental_available', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('season_start', sa.Integer(), nullable=True),
    sa.Column('season_end', sa.Integer(), nullable=True),
    sa.Column('photo_1', sa.String(), nullable=True),
    sa.Column('photo_2', sa.String(), nullable=True),
    sa.Column('photo_3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kayak_details_id'), 'kayak_details', ['id'], unique=False)
    op.create_index(op.f('ix_kayak_details_spot_id'), 'kayak_details', ['spot_id'], unique=False)
    op.create_table('motorhome_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('surface_type', sa.String(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('has_electricity', sa.Boolean(), nullable=True),
    sa.Column('has_dump_station', sa.Boolean(), nullable=True),
    sa.Column('max_stay_nights', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_id', name='uq_review_user_spot')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_spot_id'), 'reviews', ['spot_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('elevation_gain', sa.Integer(), nullable=True),
    sa.Column('elevation_loss', sa.Integer(), nullable=True),
    sa.Column('max_altitude', sa.Integer(), nullable=True),
    sa.Column('min_altitude', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('technical_level', sa.String(), nullable=True),
    sa.Column('physical_demand', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_spot_id'), 'routes', ['spot_id'], unique=False)
    op.create_table('spot_amenities',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id', 'amenity_id')
    )
    op.create_table('spot_categories',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spot_id', 'category_id')
    )
    op.create_table('spot_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_images_id'), 'spot_images', ['id'], unique=False)
    op.create_index(op.f('ix_spot_images_spot_id'), 'spot_images', ['spot_id'], unique=False)
    op.create_table('surf_beach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('class_type', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('equipment_include', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('season_start', sa.Integer(), nullable=True),
    sa.Column('season_end', sa.Integer(), nullable=True),
    sa.Column('photo_1', sa.String(), nullable=True),
    sa.Column('photo_2', sa.String(), nullable=True),
    sa.Column('photo_3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surf_beach_id'), 'surf_beach', ['id'], unique=False)
    op.create_index(op.f('ix_surf_beach_spot_id'), 'surf_beach', ['spot_id'], unique=False)
    op.create_table('trekking_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Boolean(), nullable=True),
    sa.Column('potable_water', sa.Boolean(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.Column('kids_friendly', sa.Boolean(), nullable=True),
    sa.Column('camping', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('fire_pits', sa.Boolean(), nullable=True),
    sa.Column('shelter', sa.Boolean(), nullable=True),
    sa.Column('accessible', sa.Boolean(), nullable=True),
    sa.Column('signal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_table('climbingroutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('bolts', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['climbingsectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climbingroutes_id'), 'climbingroutes', ['id'], unique=False)
    op.create_table('glamping_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glamping_id', sa.Integer(), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('private_bathroom', sa.Boolean(), nullable=True),
    sa.Column('electricity', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('breakfast_included', sa.Boolean(), nullable=True),
    sa.Column('pet_friendly', sa.Boolean(), nullable=True),
    sa.Column('heating', sa.Boolean(), nullable=True),
    sa.Column('air_conditioning', sa.Boolean(), nullable=True),
    sa.Column('kitchen', sa.Boolean(), nullable=True),
    sa.Column('towels_included', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['glamping_id'], ['glamping_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('glamping_id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_table('kayak_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kayak_details_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kayak_details_id'], ['kayak_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kayak_details_id', name='uq_kayakreview_user_detail')
    )
    op.create_index(op.f('ix_kayak_reviews_kayak_details_id'), 'kayak_reviews', ['kayak_details_id'], unique=False)
    op.create_table('surf_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surf_beach_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['surf_beach_id'], ['surf_beach.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'surf_beach_id', name='uq_surfreview_user_beach')
    )
    op.create_index(op.f('ix_surf_reviews_surf_beach_id'), 'surf_reviews', ['surf_beach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surf_reviews_surf_beach_id'), table_name='surf_reviews')
    op.drop_table('surf_reviews')
    op.drop_index(op.f('ix_kayak_reviews_kayak_details_id'), table_name='kayak_reviews')
    op.drop_table('kayak_reviews')
    op.drop_table('glamping_amenities')
    op.drop_index(op.f('ix_climbingroutes_id'), table_name='climbingroutes')
    op.drop_table('climbingroutes')
    op.drop_table('trekking_details')
    op.drop_index(op.f('ix_surf_beach_spot_id'), table_name='surf_beach')
    op.drop_index(op.f('ix_surf_beach_id'), table_name='surf_beach')
    op.drop_table('surf_beach')
    op.drop_index(op.f('ix_spot_images_spot_id'), table_name='spot_images')
    op.drop_index(op.f('ix_spot_images_id'), table_name='spot_images')
    op.drop_table('spot_images')
    op.drop_table('spot_categories')
    op.drop_table('spot_amenities')
    op.drop_index(op.f('ix_routes_spot_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_reviews_spot_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('motorhome_details')
    op.drop_index(op.f('ix_kayak_details_spot_id'), table_name='kayak_details')
    op.drop_index(op.f('ix_kayak_details_id'), table_name='kayak_details')
    op.drop_table('kayak_details')
    op.drop_index(op.f('ix_glamping_details_spot_id'), table_name='glamping_details')
    op.drop_table('glamping_details')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('idx_experiences_spot_id', table_name='experiences')
    op.drop_index('idx_experiences_category_id', table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_climbingsectors_spot_id'), table_name='climbingsectors')
    op.drop_index(op.f('ix_climbingsectors_id'), table_name='climbingsectors')
    op.drop_table('climbingsectors')
    op.drop_table('camping_details')
    op.drop_index(op.f('ix_spots_owner_email'), table_name='spots')
    op.drop_index(op.f('ix_spots_owner_deleted_at'), table_name='spots')
    op.drop_index(op.f('ix_spots_is_approved'), table_name='spots')
    op.drop_index(op.f('ix_spots_id'), table_name='spots')
    op.drop_index(op.f('ix_spots_department'), table_name='spots')
    op.drop_index(op.f('ix_spots_created_at'), table_name='spots')
    op.drop_index(op.f('ix_spots_category_id'), table_name='spots')
    op.drop_table('spots')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_amenities_id'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
