"""reclamos de lugares

spot_claims: pedidos para hacerse cargo de un lugar sugerido por un
visitante (claims.py).

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-07 14:57:51.577320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_claims_id'), 'spot_claims', ['id'], unique=False)
    op.create_index(op.f('ix_spot_claims_spot_id'), 'spot_claims', ['spot_id'], unique=False)
    op.create_index(op.f('ix_spot_claims_status'), 'spot_claims', ['status'], unique=False)
    op.create_index(op.f('ix_spot_claims_user_email'), 'spot_claims', ['user_email'], unique=False)
    op.create_index('uq_claim_pending', 'spot_claims', ['spot_id', 'user_email'], unique=True, postgresql_where=sa.text("status = 'pending'"), sqlite_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_claim_pending', table_name='spot_claims', postgresql_where=sa.text("status = 'pending'"), sqlite_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_spot_claims_user_email'), table_name='spot_claims')
    op.drop_index(op.f('ix_spot_claims_status'), table_name='spot_claims')
    op.drop_index(op.f('ix_spot_claims_spot_id'), table_name='spot_claims')
    op.drop_index(op.f('ix_spot_claims_id'), table_name='spot_claims')
    op.drop_table('spot_claims')
    # ### end Alembic commands ###
