"""datos de sectores

climbingsectors: aproximacion, sol/sombra y tipo de roca (null = no se).

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-07 15:02:50.709692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climbingsectors', sa.Column('approach_minutes', sa.Integer(), nullable=True))
    op.add_column('climbingsectors', sa.Column('sun_exposure', sa.String(), nullable=True))
    op.add_column('climbingsectors', sa.Column('rock_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climbingsectors', 'rock_type')
    op.drop_column('climbingsectors', 'sun_exposure')
    op.drop_column('climbingsectors', 'approach_minutes')
    # ### end Alembic commands ###
