"""datos de escuelas y kayak

surf_beach: niveles e idiomas; kayak_details: guia y chaleco (null = no se).

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-07 15:07:52.020904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kayak_details', sa.Column('includes_guide', sa.Boolean(), nullable=True))
    op.add_column('kayak_details', sa.Column('includes_life_jacket', sa.Boolean(), nullable=True))
    op.add_column('surf_beach', sa.Column('levels', sa.JSON(), nullable=True))
    op.add_column('surf_beach', sa.Column('languages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_beach', 'languages')
    op.drop_column('surf_beach', 'levels')
    op.drop_column('kayak_details', 'includes_life_jacket')
    op.drop_column('kayak_details', 'includes_guide')
    # ### end Alembic commands ###
