"""visitas de lugares

spot_views: una visita por persona, lugar y dia (views.py), sin IPs ni
emails. Se junta para sumarla mas adelante a la metrica de populares.

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-07 17:34:08.238444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('viewer_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id', 'day', 'viewer_hash', name='uq_spot_view_daily')
    )
    op.create_index(op.f('ix_spot_views_day'), 'spot_views', ['day'], unique=False)
    op.create_index(op.f('ix_spot_views_spot_id'), 'spot_views', ['spot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_views_spot_id'), table_name='spot_views')
    op.drop_index(op.f('ix_spot_views_day'), table_name='spot_views')
    op.drop_table('spot_views')
    # ### end Alembic commands ###
