"""descripcion y precio de escuelas y kayaks

Escuelas de surf y servicios de kayak: descripción, precio "desde" (pesos)
y una nota libre del precio ("por clase", "alquiler por hora").

Kayak, alquiler: la columna tenía default=False, así que el "no sé" del
formulario se guardaba como "no". Los False que hay no se distinguen de un
"no sé", así que pasan a null (no sé); los True quedan.

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-09 10:48:09.184763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kayak_details', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('kayak_details', sa.Column('price_from', sa.Integer(), nullable=True))
    op.add_column('kayak_details', sa.Column('price_note', sa.String(length=60), nullable=True))
    op.add_column('surf_beach', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('surf_beach', sa.Column('price_from', sa.Integer(), nullable=True))
    op.add_column('surf_beach', sa.Column('price_note', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE kayak_details SET rental_available = NULL WHERE rental_available = false")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_beach', 'price_note')
    op.drop_column('surf_beach', 'price_from')
    op.drop_column('surf_beach', 'description')
    op.drop_column('kayak_details', 'price_note')
    op.drop_column('kayak_details', 'price_from')
    op.drop_column('kayak_details', 'description')
    # ### end Alembic commands ###
