"""descripcion de rutas y slugs

routes.description: la página de la ruta de trekking tenía el bloque de
descripción, pero la columna no existía.

Rutas y sectores sin slug (los cargados antes de que se generara) no tenían
página: se les genera del nombre, con la misma regla que slugs.py.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-09 11:21:38.431607

"""
from typing import Sequence, Union

import re

from alembic import op
import sqlalchemy as sa


def _slug(name: str) -> str:
    # Copia de slugs.generate_slug: una migración no depende del código de la app.
    slug = (name or "").lower().strip()
    for pattern, repl in ((r"[áàäâ]", "a"), (r"[éèëê]", "e"), (r"[íìïî]", "i"), (r"[óòöô]", "o"), (r"[úùüû]", "u"), (r"[ñ]", "n")):
        slug = re.sub(pattern, repl, slug)
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug.strip("-")


# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, Sequence[str], None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    conn = op.get_bind()
    for table in ("routes", "climbingsectors"):
        rows = conn.execute(sa.text(f"SELECT id, name FROM {table} WHERE slug IS NULL OR slug = ''")).all()
        for row in rows:
            conn.execute(sa.text(f"UPDATE {table} SET slug = :slug WHERE id = :id"), {"slug": _slug(row.name) or str(row.id), "id": row.id})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'description')
    # ### end Alembic commands ###
