"""fotos de rutas sectores y vias

item_photos: hasta 3 fotos por ruta de trekking, sector o vía de escalada.
Una tabla para los tres (exactamente una FK cargada), con revisión como
los aportes. Ver item_photos.py.

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-09 11:32:02.876312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: Union[str, Sequence[str], None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('trekking_route_id', sa.Integer(), nullable=True),
    sa.Column('climbing_sector_id', sa.Integer(), nullable=True),
    sa.Column('climbing_route_id', sa.Integer(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.CheckConstraint('(CASE WHEN trekking_route_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN climbing_sector_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN climbing_route_id IS NULL THEN 0 ELSE 1 END) = 1', name='item_photos_one_target'),
    sa.ForeignKeyConstraint(['climbing_route_id'], ['climbingroutes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['climbing_sector_id'], ['climbingsectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trekking_route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_photos_climbing_route_id'), 'item_photos', ['climbing_route_id'], unique=False)
    op.create_index(op.f('ix_item_photos_climbing_sector_id'), 'item_photos', ['climbing_sector_id'], unique=False)
    op.create_index(op.f('ix_item_photos_id'), 'item_photos', ['id'], unique=False)
    op.create_index(op.f('ix_item_photos_is_approved'), 'item_photos', ['is_approved'], unique=False)
    op.create_index(op.f('ix_item_photos_spot_id'), 'item_photos', ['spot_id'], unique=False)
    op.create_index(op.f('ix_item_photos_trekking_route_id'), 'item_photos', ['trekking_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_photos_trekking_route_id'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_spot_id'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_is_approved'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_id'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_climbing_sector_id'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_climbing_route_id'), table_name='item_photos')
    op.drop_table('item_photos')
    # ### end Alembic commands ###
