"""recorrido de rutas de trekking

route_tracks: el recorrido de una ruta (de un GPX, simplificado), con
distancia y desnivel calculados. Uno por ruta, con revisión como los
aportes. Ver route_tracks.py.

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-09 11:42:43.657246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0020'
down_revision: Union[str, Sequence[str], None] = '0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain', sa.Integer(), nullable=True),
    sa.Column('elevation_loss', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id')
    )
    op.create_index(op.f('ix_route_tracks_id'), 'route_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_route_tracks_is_approved'), 'route_tracks', ['is_approved'], unique=False)
    op.create_index(op.f('ix_route_tracks_spot_id'), 'route_tracks', ['spot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_tracks_spot_id'), table_name='route_tracks')
    op.drop_index(op.f('ix_route_tracks_is_approved'), table_name='route_tracks')
    op.drop_index(op.f('ix_route_tracks_id'), table_name='route_tracks')
    op.drop_table('route_tracks')
    # ### end Alembic commands ###
